# Role to nstall common packages
---
- name: Install Packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - tree
    - vim
    - nmap
    - tmux
    - htop
    - curl
    - unzip
    - traceroute
    - git
  tags:
    - common_packages

- name: Install ipmitool if needed
  apt:
    name: ipmitool
    state: present
    update_cache: no
  when: "'local' in group_names"
  tags:
    - common_packages
