# Role to install and configure rsyslog
---
  - name: Install rsyslog
    apt:
      name: rsyslog
      state: present
      update_cache: true
      cache_valid_time: 3600
    tags:
      - common
      - rsyslog
      
  - name: Copy rsyslog.conf
    copy:
      src: rsyslog.conf
      dest: /etc/rsyslog.conf
      owner: root
      group: root
      mode: 0600
    tags:
      - common
      - rsyslog
      
  - name: Restart rsyslog service
    service:
      name: rsyslog
      state: restarted
    tags:
      - common
      - rsyslog
