---

- name: Install Gitlab Repo
  shell: curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh | sudo bash
  tags:
    - gitlab_runner

- name: Install gitlab-runner package
  apt:
    name: gitlab-runner
    state: present
  notify:
    - Register Runner
  tags:
    - gitlab_runner

- name: Upload Runner Config File
  template:
    src: config.toml.j2
    dest: /etc/gitlab-runner/config.toml
    owner: root
    group: root
    mode: 0600
  tags:
    - gitlab_runner

- name: Install Docker GPG Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - gitlab_runner

- name: Install Docker Repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
  tags:
    - gitlab_runner

- name: Install Docker
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    update_cache: yes
  tags:
    - gitlab_runner
