# Role to install ISC DHCP server and configure as primary
---
  - name: Install isc-dhcp
    apt:
      name: isc-dhcp-server
      state: present
      update_cache: yes
      cache_valid_time: 3600
    tags:
      - dhcp

  - name: Copy dhcpd.conf
    copy:
      src: dhcpd.conf
      dest: /etc/dhcp/dhcpd.conf
      owner: root
      group: root
      mode: 0600
    tags:
      - dhcp

  - name: Restart isc-dhcp
    service:
      name: isc-dhcp-server
      state: restarted
    tags:
      - dhcp
