all:
  vars:
    location: Virtual
    contact: ryan@dorwinia.com
    ansible_python_interpreter: /usr/bin/python3
  children:

    test:
      hosts:
        ans-1.dorwinia.com:
        ans-2.dorwinia.com:
  
    mgmt:
      hosts:
        config.dorwinia.com:
        graylog.dorwinia.com:

    dns:
      hosts:
        dns-1.dorwinia.com:
          ansible-host: 192.168.1.11
        dns-2.dorwinia.com:
          ansible-host: 192.168.1.12
        dns-3.dorwinia.com:
          ansible-host: 192.168.1.13

    dhcp:
      hosts:
        dhcp-1.dorwinia.com:
          primary: true
        dhcp-2.dorwinia.com:
          primary: false

    wireguard:
      hosts:
        wireguard-1.dorwinia.com:
          primary: true
        wireguard-2.dorwinia.com:
          primary: false
    
    gitlab-runners:
      hosts:
        gitlab-runner-1.dorwinia.com:
        gitlab-runner-2.dorwinia.com:

    prod:
      hosts:
        nginx.dorwinia.com:
        git.dorwinia.com:
        plex.dorwinia.com:
