all:
  vars:
    #ansible_python_interpreter: /usr/bin/python3
  children:

    mgmt:
      hosts:
        config.dorwinia.com:

    network:
      children:
        unifi:
          hosts:
            unifi.dorwinia.com:
        netbox:
          hosts:
            netbox.dorwinia.com:

    lbs:
      hosts:
        lb-1.dorwinia.com:
