all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:

    mgmt:
      hosts:
        config.dorwinia.com:

    network:
      children:
        nat:
          hosts:
            nat.dorwinia.com:
        wireguard:
          hosts:
            wireguard.dorwinia.com:

    kubernetes:
      children:
        kube_controller:
          hosts:
            kube-con-1.dorwinia.com:
        # K8s worker nodes are managed by aws_spot_fleet
        # No ansible required
        #kube_worker:
          #hosts:
            #kube-wor-[1:3].dorwinia.com:

    lbs:
      hosts:
        lb-1.dorwinia.com:
