all:
  vars:
    location: Virtual
    contact: ryan@dorwinia.com
    ansible_python_interpreter: /usr/bin/python3
  children:

    test:
      hosts:
        ans-1.dorwinia.com:
        ans-2.dorwinia.com:
  
    mgmt:
      hosts:
        config.dorwinia.com:
        graylog.dorwinia.com:

    dns:
      hosts:
        dns-1.dorwinia.com:
          ansible-host: 192.168.1.11
        dns-2.dorwinia.com:
          ansible-host: 192.168.1.12
        dns-3.dorwinia.com:
          ansible-host: 192.168.1.13

    dhcp:
      hosts:
        dhcp-1.dorwinia.com:
          dhcp-primary: true
        dhcp-2.dorwinia.com:
          dhcp-primary: false

    network:
      hosts:
        tun-0.dorwinia.com:
          wireguard-primary: true
        tun-1.dorwinia.com:
          wireguard-primary: false
        tun-2.dorwinia.com:
          wireguard-primary: false
    
    
    gitlab_runners:
      hosts:
        gitlab-runner-1.dorwinia.com:
        gitlab-runner-2.dorwinia.com:

    kubernetes:
      children:
        kube_controller:
          hosts:
            kube-controller-1.dorwinia.com:
        kube_worker:
          hosts:
            kube-worker-1.dorwinia.com:
            kube-worker-2.dorwinia.com:
            kube-worker-3.dorwinia.com:

    prod:
      hosts:
        nginx.dorwinia.com:
        git.dorwinia.com:
        plex.dorwinia.com:
