# Role to configure Bind9 to be Primary Master
---
# Install Bind9
- name: Install Bind9
  apt:
    name: bind9
    state: present
    update_cache: yes
  tags:
    - dns

# Copy configuration files
- name: Copy Configuration files
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: root
    group: bind
    mode: 0644
  with_items:
    - src: named.conf
      dest: /etc/bind/named.conf
    - src: named.conf.options
      dest: /etc/bind/named.conf.options
    - src: db.dorwinia.com
      dest: /var/lib/bind/db.dorwinia.com
    - src: db.local.dorwinia.com
      dest: /var/lib/bind/db.local.dorwinia.com
    - src: db.guest.dorwinia.com
      dest: /var/lib/bind/db.guest.dorwinia.com
    - src: db.192
      dest: /var/lib/bind/db.192
    - src: db.40.0.10
      dest: /var/lib/bind/db.40.0.10
    - src: db.50.0.10
      dest: /var/lib/bind/db.50.0.10
  tags:
    - dns

# Restart Bind9
- name: Restart Bind9
  service:
    name: bind9
    state: restarted
  tags:
    - dns

