" .vimrc
" Ryan Schouweieler

" Basic visual indicators
set cursorline
set number

" Tab settings
set textwidth=0 nosmartindent tabstop=2 shiftwidth=2 softtabstop=2 expandtab

" Start scrolling near screen boundaries
set so=3

" Turn off annoying ding sound
set visualbell

" Folding Settings
set foldmethod=indent
set foldlevel=10

" Enable using modelines
set modeline
