# Role to install and configure nginx
---
  # Install nginx
  - name: Install nginx
    apt:
      name: nginx
      state: present
      update_cache: true
      cache_valid_time: 3600
    tags:
      - nginx

  # Install Certbot 
  - name: Add repository
    apt_repository:
            repo: ppa:certbot/certbot

  - name: Install Certbot
    apt:
      name: certbot python-certbot-nginx
      state: present
      update_cache: true
      cache_valid_time: 3600
    tags:
      - nginx

  # Copy Configuration Files
  - name: Copy dorwinia.conf
    copy:
      src: dorwinia.conf
      dest: /etc/nginx/conf.d/dorwinia.conf
      owner: root
      group: root
      mode: 0600
    tags:
      - nginx
      
  - name: Copy index file
    copy:
      src: index.nginx-debian.html
      dest: /var/www/html/index.nginx-debian.html
      owner: root
      group: root
      mode: 0755
    tags:
      - nginx

  # Restart nginx
  - name: Restart nginx service
    service:
      name: nginx
      state: restarted
    tags:
      - nginx
