# Role to install and Bind 9
---
# Install Bind9
  - name: Install Bind9
    apt:
      name: bind9
      state: present
      update_cache: yes
    tags:
      - dns

# Restart Bind9
  - name: Restart Bind9
    service:
      name: bind9
      state: restarted
    tags:
      - dns

