- name: Install Google GPG Key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  tags:
    - kubernetes
    - kube_controller
    - kube_worker

- name: Install Kubernetes Repo
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
  tags:
    - kubernetes
    - kube_controller
    - kube_worker

- name: Install Kubernetes Packages
  apt:
    name: ['kubelet', 'kubeadm', 'kubectl']
    update_cache: yes
    state: present
  tags:
    - kubernetes
    - kube_controller
    - kube_worker

- name: Prevent Unintended Upgrades to Kubernetes
  dpkg_selections:
    name: ['kubelet', 'kubeadm', 'kubectl']
    selection: hold
  tags:
    - kubernetes
    - kube_controller
    - kube_worker

- name: Disable Swap
  shell: |
    swapoff -a
  tags:
    - kubernetes
    - kube_controller
    - kube_worker

- name: Disable Swap in fstab to prevent re-enabling
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  
