---
- name: Enable IP forwarding on reboot
  lineinfile:
    path: /etc/sysctl.conf
    regex: '^#?net.ipv4.ip_forward=1'
    line: net.ipv4.ip_forward = 1
    state: present
  notify:
    - Enable IP Forwarding
  tags:
    - nat

- name: Add iptables NAT rule to rc.local  
  lineinfile:
    path: /etc/rc.local
    line: iptables -t nat -A POSTROUTING -o ens5 -s 10.1.0.0/16 -j MASQUERADE
    state: present
    create: yes
  notify:
    - Enable NAT
  tags:
    - nat

- name: Flush handlers
  meta: flush_handlers
  tags:
    - nat
