---
- name: Enable IP forwarding on reboot
  lineinfile:
    path: /etc/sysctl.conf
    regex: '^#?net.ipv4.ip_forward=1'
    line: net.ipv4.ip_forward=1
    state: present
  notify:
    - Enable IP Forwarding
  tags:
    - nat

- name: Ensure iptables rule is persistent on reboot
  cron:
    name: Ensure iptables rule is persistent on reboot
    job: "sleep 10 && /usr/sbin/iptables -t nat -A POSTROUTING -o {{ansible_default_ipv4.interface}} -j MASQUERADE"
    special_time: reboot
  notify:
    - Enable NAT
  tags:
    - nat
