# Role to configure Bind9 to be Secondary Slave
---
# Copy configuration files
  - name: Copy named.conf
    copy:
      src: named.conf
      dest: /etc/bind/named.conf
      owner: root
      group: bind
      mode: 0644
    tags:
      - dns

  - name: Copy named.conf.options
    copy:
      src: named.conf.options
      dest: /etc/bind/named.conf.options
      owner: root
      group: bind
      mode: 0644
    tags:
      - dns

# Restart Bind9
  - name: Restart Bind9
    service:
      name: bind9
      state: restarted
    tags:
      - dns

