# Role to configure users and custom user settings
---

# Initial user setup
- name: ensure sudo group exists
  group:
    name: sudo
    state: present
  tags:
    - users

- name: add dorwin user
  user:
    name: dorwin
    password: ***REMOVED***
    groups: sudo
    shell: /bin/bash
    append: yes
    state: present
  tags:
    - users

# Copy user config files
- name: Copy dorwin's config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: dorwin
    mode: 0644
  with_items: 
    - src: vimrc
      dest: /home/dorwin/.vimrc 
    - src: inputrc
      dest: /home/dorwin/.inputrc 
  tags:
    - users

# Remove users
- name: Remove automaton user
  user:
    name: automaton
    state: absent
    remove: true
  tags:
    - users
