# Role to configure users and custom user settings
---

# Initial user setup
- name: ensure sudo group exists
  group:
    name: sudo
    state: present
  tags:
    - user_config

- name: add dorwin user
  user:
    name: dorwin
    password: ***REMOVED***
    groups: sudo
    shell: /bin/bash
    append: yes
    state: present
  tags:
    - user_config

# Copy user config files
- name: Copy dorwin's config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: dorwin
    mode: 0644
  with_items: 
    - src: vimrc
      dest: /home/dorwin/.vimrc 
    - src: inputrc
      dest: /home/dorwin/.inputrc 
  tags:
    - user_config

# Remove users
- name: Remove disabled users
  user:
    name: "{{ item }}"
    state: absent
    remove: true
  with_items:
    - automaton
    - packer
  tags:
    - user_config
