- name: Install Docker GPG Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  tags:
    - docker

- name: Install Docker Repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian trixie stable"
    state: present
  tags:
    - docker

- name: Install Docker
  ansible.builtin.apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    update_cache: yes
  tags:
    - docker
