# Playbook to run tasks to maintain the whole environment

- name: Common Configuration
  hosts: terraform-test.dorwinia.com
  become: yes
  become_user: root
  roles:
    - user
    - common_packages
