# Playbook to run tasks to maintain the whole environment

# User config: ------------------------------------------
- name: Configure users
  hosts: all
  become: yes
  become_user: root
  roles:
    - users_config

# Install standard packages: ---------------------------
#- name: Install standard packages
#  hosts: all
#  become: yes
#  become_user: root
#  roles:
#    - snmp_install

- name: Install standard packages
  hosts: all
  become: yes
  become_user: root
  roles:
    - snmp_config

# Run various updates: ----------------------------------
- name: Update OS'es
  hosts: all
  become: yes
  become_user: root
  roles:
    - os_update

- name: Update PiHole
  hosts: 192.168.1.13
  become: yes
  become_user: root
  roles:
    - pihole_update

