# Generic playbook to create a very basic playbook
# Designed to be able to run against any host

- name: Run common roles
  hosts: all
  become: yes
  become_user: root
  roles:
    - user_config
    - rsyslog_config
    - common_packages
    - os_update
