# Generic playbook to create a very basic playbook
# Designed to be able to run against any host

- name: Run common roles
  hosts: all
  become: yes
  become_user: root
  roles:
    - users
    - rsyslog
    - common_packages
    - os_update
