# Playbook to run tasks to maintain the whole environment

# User config: ------------------------------------------
- name: Configure users
  hosts: all
  become: yes
  become_user: root
  roles:
    - user_config

# Install standard packages: ---------------------------

- name: Install standard packages
  hosts: all
  become: yes
  become_user: root
  roles:
    - common_packages

# Run various updates: ----------------------------------
- name: Update System
  hosts: all
  become: yes
  become_user: root
  roles:
    - os_update
