- name: Update All
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: Update
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade
      apt:
        upgrade: dist

    - name: Autoremove
      apt:
        autoremove: yes

- name: Update PiHole
  hosts: dns-3.dorwinia.com
  become: yes
  become_user: root
  roles:
    - dns_pihole_update
