- name: Update OS'es
  hosts: all
  become: yes
  become_user: root
  roles:
    - os_update

- name: Update PiHole
  hosts: 192.168.1.13
  become: yes
  become_user: root
  roles:
    - pihole_update
