# Generic playbook to create a very basic playbook
# Designed to be able to run against any host

- name: Install and setup Wireguard Site-to-Site VPN
  gather_facts: no
  hosts: network
  become: yes
  become_user: root
  roles:
    - user
    - wireguard
