---

- name: Install wireguard
  apt:
    name: wireguard
    state: present
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - wireguard

- name: Check if IP forwarding is enabled
  command: sysctl net.ipv4.ip_forward
  register: forwarding_state
  changed_when: False
  tags:
    - wireguard

- name: Enable IP forwarding if needed
  command: sysctl net.ipv4.ip_forward=1
  when: forwarding_state.stdout == "net.ipv4.ip_forward = 0"
  tags:
    - wireguard

- name: Upload sysctl.conf to keep IP forwarding persistent
  copy:
    src: sysctl.conf
    dest: /etc/sysctl.conf
    mode: 0644
    owner: root
    group: root
  tags:
    - wireguard

- name: Upload tun-0 wg1 config files
  when: inventory_hostname == "tun-0.dorwinia.com"
  notify: reload_wireguard
  template:
    src: tun-0-wg1.conf.j2
    dest: /etc/wireguard/wg1.conf
  tags:
    - wireguard

- name: Upload tun-0 wg2 config files
  when: inventory_hostname == "tun-0.dorwinia.com"
  notify: reload_wireguard
  template:
    src: tun-0-wg2.conf.j2
    dest: /etc/wireguard/wg2.conf
  tags:
    - wireguard

- name: Upload tun-1 config file
  when: inventory_hostname == "tun-1.dorwinia.com"
  notify: reload_wireguard
  template:
    src: tun-1-wg1.conf.j2
    dest: /etc/wireguard/wg1.conf
  tags:
    - wireguard

- name: Upload tun-2 config file
  when: inventory_hostname == "tun-2.dorwinia.com"
  notify: reload_wireguard
  template:
    src: tun-2-wg2.conf.j2
    dest: /etc/wireguard/wg2.conf
  tags:
    - wireguard

- name: Activate links on boot
  systemd:
    name: "wg-quick@wg{{ item }}"
    enabled: yes
  loop: "{{ tun_nums }}"
  tags:
    - wireguard
